### ISSUE TITLE
能否增加隐藏状态栏图标功能

### ISSUE THREAD

**Issue by lianginx** [DreamSaddle/MacCopier#1]
**首先谢谢您做的应用，非常方便！**

请问能否增加 `隐藏状态栏图标` 的功能，因为这个应用是要长时间运行在后台的，去掉状态栏图标后能够达到更加“无感”的体验。

**Comment by DreamSaddle** [comment]
我目前使用了 Bartender 这样的隐藏部分状态栏图标的工具，倒没这个烦恼。

不过这也是一个问题，我回头考虑加上吧。
因为是没有 dock 栏图标且没有主窗口，所以，**自动粘贴**以及**登录时启动**这两个功能选项就只能在状态栏菜单中进行勾选。

我简单想了一下大致实现逻辑为：状态栏菜单增加 **隐藏状态栏图标** 选项。如果再次从 启动台 打开 MacCopier 时，则恢复状态栏图标的显示。

**Comment by DreamSaddle** [comment]
已增加此功能选项。

[commit](https://github.com/DreamSaddle/MacCopier/commit/c49736986acd19eb9b494a72aea84a7c87bec313)
[release](https://github.com/DreamSaddle/MacCopier/releases/tag/3.0)
