### ISSUE TITLE
错误:我在尝试打开应用时失败

### ISSUE THREAD

**Issue by Heart-Breezer** [DreamSaddle/MacCopier#10]
在下载3.3版本的MacCopier.zip后,进行解压缩和移动至应用程序文件夹,尝试打开时报错.
<img width="267" alt="截屏2024-11-19 19 41 23" src="https://github.com/user-attachments/assets/bec7f2e5-8c9c-44c8-83f5-add20e547ad0">
我并没有给予任何权限,且重新下载了两次,并没有解决问题

**Comment by DreamSaddle** [comment]
1. 文件损坏请看一下[这个教程](https://juejin.cn/post/7239589685975121980)。
2. 是需要给权限的哟，否则无法读取短信数据库文件。

**Comment by Heart-Breezer** [comment]
我解决了这个问题,非常感谢.
