### ISSUE TITLE
3.3版本包损坏

### ISSUE THREAD

**Issue by Ellioben** [DreamSaddle/MacCopier#11]
release里的3.3启动报错。m系列芯片
![image](https://github.com/user-attachments/assets/5c5bb2d4-dcc7-453a-9875-f1bc221169d9)

---
换成3.2的没问题

谢谢作者😀

**Comment by DreamSaddle** [comment]
参照这个 #10 解决。

**Comment by Ellioben** [comment]
> 参照这个 #10 解决。

哦哦好的，谢谢啦
