### ISSUE TITLE
验证码复制错误

### ISSUE THREAD

**Issue by Kerwin1202** [DreamSaddle/MacCopier#2]
```
您的验证码为 5258，10分钟内有效。(来自1069184530604170)
```
这时候会复制 604170 而不是 5258

**Comment by Kerwin1202** [comment]
提完之后才发现今天有个新版本，不知道是否解决了，后面有短信我再看看

**Comment by DreamSaddle** [comment]
最新版的[这一次提交](https://github.com/DreamSaddle/MacCopier/commit/d731c5cac385e310bb281f96d3d19beac232a97a)修改了只会复制第一个匹配的，匹配你这条短信就是 `5258`。旧版本会挨个复制所有匹配。
