### ISSUE TITLE
验证码提取有误

### ISSUE THREAD

**Issue by lucienhsu** [DreamSaddle/MacCopier#5]
您好，xxxxxx-7576，本次登录验证码为：496463，验证码的有效期：xxxxxxxx

以上识别到了 `7576`，识别错误。

**Comment by DreamSaddle** [comment]
目前就是通过正则表达式匹配的首个满足规则的内容。
我还没有找到一个其它的较好的识别方案。

**Comment by lucienhsu** [comment]
一般短信会在关键字后面+验证码，
关键字如：验证码+123123，把提取的时机放在关键字后面？？？

**Comment by DreamSaddle** [comment]
这也不是一个好的解决方案，正则表达式匹配是“死”的。
我想办法解决吧。

**Comment by yuhangch** [comment]
提供另一个 case: 【1024CODE】欢迎使用，您的手机验证码是636246。如非本人操作，请忽略本短信
提取了 1024 。

**Comment by DreamSaddle** [comment]
> 提供另一个 case: 【1024CODE】欢迎使用，您的手机验证码是636246。如非本人操作，请忽略本短信 提取了 1024 。

嗯是的，正则表达式匹配就是有这个问题。

**Comment by laleoarrow** [comment]
是否可以加一个if条件 当出现“验证码：”的时候提取后面的数字

**Comment by DreamSaddle** [comment]
> 是否可以加一个if条件 当出现“验证码：”的时候提取后面的数字

并不是一个最终解决方案，针对某些场景还是有用。
不过根据 #7 这个问题处理后，已经能满足绝大多数的验证码提取了。

**Comment by tongjiann** [comment]
> > 是否可以加一个if条件 当出现“验证码：”的时候提取后面的数字
> 
> 并不是一个最终解决方案，针对某些场景还是有用。 不过根据 #7 这个问题处理后，已经能满足绝大多数的验证码提取了。

当使用\b边界符来判断时，部分时候也会导致验证码提取失败，正则：`\b\d{4,6}\b`，短信：`【阿里云】您正在进行短信登录，验证码123456，切勿将验证码泄露于他人，本条验证码有效期15分钟。`

**Comment by DreamSaddle** [comment]
@lucienhsu @yuhangch @laleoarrow @tongjiann  [3.3](https://github.com/DreamSaddle/MacCopier/releases/tag/3.3)版本增加了Python脚本支持，可以用本地大模型解处理，当然线上的也可以。
