### ISSUE TITLE
不兼容 macOS 11（Big Sur）

### ISSUE THREAD

**Issue by lianginx** [DreamSaddle/MacCopier#6]
我最近更新了体验版系统，太卡了，就重装了 11 版本，然后发现程序要求最低 12 版本

这个是处于什么考虑？可以兼容一下 11 吗？

![image](https://github.com/DreamSaddle/MacCopier/assets/21002250/3f24ccb9-ba43-47dd-a658-fb15bf9834d3)

**Comment by DreamSaddle** [comment]
您方便自己重新编译一下吗？

**Comment by DreamSaddle** [comment]
下载[这个版本](https://github.com/DreamSaddle/MacCopier/releases/tag/3.1)

**Comment by lianginx** [comment]
> 下载[这个版本](https://github.com/DreamSaddle/MacCopier/releases/tag/3.1)

非常感谢！明天端午节啦，放假好好休息~
