### ISSUE TITLE
短信内容验证码识别有误

### ISSUE THREAD

**Issue by tisfeng** [DreamSaddle/MacCopier#7]
## 问题

如下短信内容，应用会自动提取出验证码 18900001，但这明显不对，这只是一个手机号

> 尊敬的客户，您反映的18900001111号码问题已受理，查询处理进度请点击 https://waphn.189.cn/ 或微信关注“湖南电信”公众号。中国电信"好服务更随心"，期待您的10分满意！

## 期望结果

不要误识别短信内容，将不是验证码的数字识别为验证码。

## 解决方案

看了一下代码，这个判断条件可以优化一下，将 "码" 改成 ”验证码“ 应该会好很多。

如果想进一步优化，可以将识别关键字列表设置成选项，让用户自定义。

```swift
            if msgText.contains("code") || msgText.contains("码") || msgText.contains("コード") || msgText.contains("認証番号") {
                do {
                    let re = try NSRegularExpression(pattern: codePattern, options: [])
                    let results = re.matches(in: msgText, range: NSRange(location: 0, length: msgText.count))
                    for result in results {
                        let code = (msgText as NSString).substring(with: result.range)
                        print("code: \(code)")
                        self.clipboard.copy(text: code)
                        if UserDefaults.standard.autoPaste {
                            self.clipboard.paste()
                        }
                        
                        break
                    }
                } catch {
                    print("Regex Error.")
                }
            }
```

**Comment by DreamSaddle** [comment]
使用正则表达式匹配都会存在这个问题，即使自定义了匹配关键字规则，也会有这个问题，只能提升一定灵活性，但并不能完全的解决匹配错误的问题。
因为是从前往后匹配的，都会存在错误匹配的情况，比如下面的例子：
```
尊敬的 18311112222 用户，你本次的验证码为 1234。
```
这种始终都会匹配到前面的手机号。

**Comment by tisfeng** [comment]
使用简单的匹配方式来实现，肯定无法做到完美，但我想说的是，用单字 "码" 来作为验证码的关键字，这显然匹配范围过大，容易误杀，改用 ”验证码“ 命中准确性至少大大提升了。

自定义，是为了应对一些特殊的验证码，比如 [中国工商银行] 的境外支付验证码 https://github.com/LeeeSe/MessAuto/pull/41 ，或者其他国家语言的用户。

**Comment by tisfeng** [comment]
至于验证码提取有误，那又是另一个问题了， 例如，可以通过设置边界检查，这样简单优化一下就不会匹配到手机号了。

```swift
let codePattern = "\\b([0-9]{4,8})\\b"
```

**Comment by tisfeng** [comment]
如果不想使用简单的关键字匹配方式，也可以考虑用机器学习，验证码短信这种文本特征都比较固定，应该比较容易学习。

**Comment by DreamSaddle** [comment]
> 至于验证码提取有误，那又是另一个问题了， 例如，可以通过设置边界检查，这样简单优化一下就不会匹配到手机号了。
> 
> ```swift
> let codePattern = "\\b([0-9]{4,8})\\b"
> ```

可以的，这倒是一个比较好得解决思路；增加自定义关键字匹配规则这个可以增加上，只要增加了这个功能后，自然也就能添加你给出来的这个规则了。

**Comment by DreamSaddle** [comment]
很好，我之前也没太深入去了解正则表达式的其他用法，我试了下，设置检查边界后确实可以减少匹配错误的概率。
又get到一个新知识点了，哈哈！
🎉🎉🎉

**Comment by DreamSaddle** [comment]
@tisfeng 如果有本地大模型可以用 [3.3](https://github.com/DreamSaddle/MacCopier/releases/tag/3.3) 版本中自定义Python脚本处理。
